from pathlib import Path
import pandas as pd,numpy as np,json,hashlib
ROOT=Path(__file__).resolve().parent
p=ROOT/'data/model_ready_hierarchical_v1/20260913T033945Z'
out=ROOT/'data/audit/hierarchical_input_v1/20260913T033945Z';out.mkdir(parents=True,exist_ok=False)
d=pd.read_csv(p/'stock_daily.csv',parse_dates=['Date']);reg=pd.read_csv(p/'registry.csv');m=pd.read_csv(p/'macro_daily.csv',parse_dates=['Date','reference_spy_session'])
identity=pd.read_csv(ROOT/'data/audit/hierarchical_identity/20260913T034024Z/identity_currency.csv')
splits=pd.read_csv(ROOT/'data/raw/hierarchical_splits_v1/20260913T034153Z/splits.csv');events=splits[splits['Capital Change Ex Date'].notna()];windows=[]
for _,event in events.iterrows():
    date=pd.Timestamp(event['Capital Change Ex Date']);x=d[d.Instrument.eq(event.Instrument)&d.Date.between(date-pd.Timedelta(days=7),date+pd.Timedelta(days=7))].copy()
    x['vendor_split_date']=date;x['vendor_adjustment_factor']=event['Adjustment Factor'];windows.append(x)
w=pd.concat(windows,ignore_index=True) if windows else pd.DataFrame();w.to_csv(out/'split_windows.csv',index=False)
checks={'34_unique_companies':len(reg)==34 and reg.Instrument.is_unique,'unique_panel_keys':not d.duplicated(['Date','Instrument']).any(),'full_grid':len(d)==34*d.Date.nunique(),'2020_2025_only':bool(d.Date.between('2020-01-01','2025-12-31').all()),'one_primary_group':bool(d.groupby('Instrument').primary_group.nunique().eq(1).all()),'all34_currencyUSD':len(identity)==34 and identity.Currency.eq('USD').all() and identity.CF_CURR.eq('USD').all(),'macro_reference_before_date':bool((m.reference_spy_session<m.Date).all()),'valid_returns_above_minusone':bool(d.return_decimal.dropna().ge(-1).all()),'valid_close_positive':bool(d.close.dropna().gt(0).all()),'split_windows_no_large_price_return_discrepancy':bool(w.return_price_discrepancy.dropna().abs().le(.15).all()),'no_large_price_return_discrepancy_all':bool(d.return_price_discrepancy.dropna().abs().le(.15).all())}
summary=dict(checks={k:bool(v) for k,v in checks.items()},all_pass=all(checks.values()),split_event_rows=len(events),split_window_rows=len(w),limits=['Split-window internal consistency is not a complete independent corporate-action audit.','Missing-date vendor placeholders were grouped as duplicates in builder audit:1073 source rows have no Date and no value. They did not enter dated model grid; no actual dated conflicting values found.','Current USD listing identity does not prove all historical membership facts.','AMRC 2025-08-05 +48.982% return retained and agrees with close change; no event explanation inferred.'],inputs={str(f.relative_to(ROOT)):hashlib.sha256(f.read_bytes()).hexdigest() for f in [p/'stock_daily.csv',p/'registry.csv',p/'macro_daily.csv']})
(out/'checks.json').write_text(json.dumps(summary,indent=2),encoding='utf-8');print(json.dumps(summary,indent=2))
for name in ['DATA_PROCESSING_LOG.md','AI_USE_LOG.md']:
    with (ROOT/name).open('a',encoding='utf-8') as f:f.write(f'\n\n## Hierarchical input verification 2026-09-13\nExecuted validate_hierarchical_input_v1.py; {sum(checks.values())}/{len(checks)} checks pass, output {out.relative_to(ROOT)}. Currency34/34USD returned by LSEG, {len(events)} split event rows checked in surrounding windows; no >15 percentage-point price/total-return mismatch. No adjustments applied to data by this audit. Vendor missing-date placeholders1073 were mislabeled duplicate rows in builder summary, all remain quarantined and none joined to dated grid. No true conflicting dated duplicate. Full corporate-action/PIT validation not claimed.\n')
